### ISSUE TITLE
handle users trying to create spaces with uppercase characters

### ISSUE THREAD

**Issue by barathrm** [hummingbard/hummingbard#2]
It seems that you're currently allowed to attempt to create spaces containing uppercase characters.

When the space is created, you're redirected to a url to that space containing the uppercase characters, and you get a 404.

**Comment by ShadowJonathan** [comment]
The problem is that synapse currently allows uppercase room IDs, there are two MSCs in progress (https://github.com/matrix-org/matrix-doc/pull/1607 and https://github.com/matrix-org/matrix-doc/pull/1597) which try to specify the room alias grammar further.

**Comment by ShadowJonathan** [comment]
![image](https://user-images.githubusercontent.com/22740616/109546035-f4dbe900-7ac9-11eb-8b82-a94f31446ab9.png)

this is the answer i got in `#matrix-spec:matrix.org` regarding the room alias grammar :I

**Comment by hummingbard** [comment]
I'm not sure why I chose to enfore lowercase in the backend, but that's what it looks like in [create.go](https://github.com/hummingbard/hummingbard/blob/8e5ac94b4b4788911aa6b9b93944bc3492e71349/client/create.go#L183). I'll taka a look at the MSCs. 

But for now I'll enforce lowercase in the space creation UI too, and redirect appropriately.

**Comment by ShadowJonathan** [comment]
Enforce lowercase on creation, but have case sensitivity in the URL if a room exists with that exact capital case, else 307 to the lowercase link?
